using System.Collections.Concurrent;
using TicTacToe.Api.Models;

namespace TicTacToe.Api.Services;

public sealed class GameService
{
    private readonly ConcurrentDictionary<Guid, Game> _games = new();
    private readonly object _scoreLock = new();
    private Scoreboard _scoreboard = new();

    public Game CreateGame(GameMode mode)
    {
        var game = new Game { Id = Guid.NewGuid(), Mode = mode };
        _games[game.Id] = game;
        return game;
    }

    public Game? GetGame(Guid id) => _games.TryGetValue(id, out var game) ? game : null;

    public Scoreboard GetScoreboard()
    {
        lock (_scoreLock)
        {
            return CopyScoreboard(_scoreboard);
        }
    }

    public void ResetScoreboard()
    {
        lock (_scoreLock)
        {
            _scoreboard = new Scoreboard();
        }
    }

    public Game MakeMove(Guid id, MoveRequest request)
    {
        var game = GetRequiredGame(id);

        lock (game)
        {
            ValidateMove(game, request);

            ApplyMove(game, request.Player, request.Row, request.Column);

            UpdateResult(game);

            if (game.Status == GameStatus.InProgress &&
                game.Mode == GameMode.Computer &&
                game.CurrentPlayer == Player.O)
            {
                var computerMove = SelectComputerMove(game);
                ApplyMove(game, Player.O, computerMove.row, computerMove.column);
                UpdateResult(game);
            }

            return game;
        }
    }

    public Game Undo(Guid id)
    {
        var game = GetRequiredGame(id);

        lock (game)
        {
            if (game.Moves.Count == 0)
                return game;

            if (game.Status != GameStatus.InProgress)
                throw new InvalidOperationException("Undo is disabled after the game is completed.");

            if (game.Mode == GameMode.Computer)
            {
                if (game.Moves[^1].Player == Player.O)
                {
                    RemoveLastMove(game);
                    if (game.Moves.Count > 0 && game.Moves[^1].Player == Player.X)
                        RemoveLastMove(game);
                }
                else
                {
                    RemoveLastMove(game);
                }
            }
            else
            {
                RemoveLastMove(game);
            }

            RecalculateState(game);
            return game;
        }
    }

    public Game ResetGame(Guid id)
    {
        var oldGame = GetRequiredGame(id);

        lock (oldGame)
        {
            var reset = new Game
            {
                Id = oldGame.Id,
                Mode = oldGame.Mode
            };

            _games[id] = reset;
            return reset;
        }
    }

    private static void ValidateMove(Game game, MoveRequest request)
    {
        if (game.Status != GameStatus.InProgress)
            throw new InvalidOperationException("The game is already completed.");

        if (game.Mode == GameMode.Computer && request.Player == Player.O)
            throw new InvalidOperationException("Computer moves are generated by the server.");

        if (request.Player != game.CurrentPlayer)
            throw new InvalidOperationException($"It is {game.CurrentPlayer}'s turn.");

        if (request.Row is < 0 or > 2 || request.Column is < 0 or > 2)
            throw new InvalidOperationException("Row and column must be between 0 and 2.");

        if (game.Board[request.Row, request.Column] is not null)
            throw new InvalidOperationException("The selected cell is already occupied.");
    }

    private static void ApplyMove(Game game, Player player, int row, int column)
    {
        game.Board[row, column] = player;
        game.Moves.Add(new Move
        {
            MoveNumber = game.Moves.Count + 1,
            Player = player,
            Row = row,
            Column = column
        });
        game.CurrentPlayer = player == Player.X ? Player.O : Player.X;
    }

    private void UpdateResult(Game game)
    {
        var winning = FindWinningCells(game);

        if (winning.Count > 0)
        {
            game.Status = GameStatus.Won;
            game.Winner = game.Board[winning[0][0], winning[0][1]];
            game.WinningCells = winning;
            ApplyScoreOnce(game);
            return;
        }

        if (game.Moves.Count == 9)
        {
            game.Status = GameStatus.Draw;
            game.Winner = null;
            game.WinningCells = [];
            ApplyScoreOnce(game);
        }
    }

    private void RecalculateState(Game game)
    {
        game.Status = GameStatus.InProgress;
        game.Winner = null;
        game.WinningCells = [];
        game.ScoreApplied = false;

        var winning = FindWinningCells(game);
        if (winning.Count > 0)
        {
            game.Status = GameStatus.Won;
            game.Winner = game.Board[winning[0][0], winning[0][1]];
            game.WinningCells = winning;
        }
        else if (game.Moves.Count == 9)
        {
            game.Status = GameStatus.Draw;
        }
    }

    private void ApplyScoreOnce(Game game)
    {
        if (game.ScoreApplied)
            return;

        lock (_scoreLock)
        {
            if (game.Winner == Player.X) _scoreboard.XWins++;
            else if (game.Winner == Player.O) _scoreboard.OWins++;
            else _scoreboard.Draws++;

            game.ScoreApplied = true;
        }
    }

    private static List<int[]> FindWinningCells(Game game)
    {
        int[][] lines =
        [
            [0,0, 0,1, 0,2],
            [1,0, 1,1, 1,2],
            [2,0, 2,1, 2,2],
            [0,0, 1,0, 2,0],
            [0,1, 1,1, 2,1],
            [0,2, 1,2, 2,2],
            [0,0, 1,1, 2,2],
            [0,2, 1,1, 2,0]
        ];

        foreach (var line in lines)
        {
            var a = game.Board[line[0], line[1]];
            var b = game.Board[line[2], line[3]];
            var c = game.Board[line[4], line[5]];

            if (a is not null && a == b && b == c)
                return [[line[0], line[1]], [line[2], line[3]], [line[4], line[5]]];
        }

        return [];
    }

    private static (int row, int column) SelectComputerMove(Game game)
    {
        var winning = FindTacticalMove(game, Player.O);
        if (winning.HasValue) return winning.Value;

        var block = FindTacticalMove(game, Player.X);
        if (block.HasValue) return block.Value;

        if (game.Board[1, 1] is null)
            return (1, 1);

        (int row, int column)[] corners = [(0,0), (0,2), (2,0), (2,2)];
        foreach (var corner in corners)
        {
            if (game.Board[corner.row, corner.column] is null)
                return corner;
        }

        for (var row = 0; row < 3; row++)
        for (var column = 0; column < 3; column++)
            if (game.Board[row, column] is null)
                return (row, column);

        throw new InvalidOperationException("No computer move is available.");
    }

    private static (int row, int column)? FindTacticalMove(Game game, Player player)
    {
        for (var row = 0; row < 3; row++)
        for (var column = 0; column < 3; column++)
        {
            if (game.Board[row, column] is not null) continue;

            game.Board[row, column] = player;
            var wins = FindWinningCells(game).Count > 0;
            game.Board[row, column] = null;

            if (wins) return (row, column);
        }

        return null;
    }

    private static void RemoveLastMove(Game game)
    {
        var move = game.Moves[^1];
        game.Board[move.Row, move.Column] = null;
        game.Moves.RemoveAt(game.Moves.Count - 1);
        game.CurrentPlayer = move.Player;
    }

    private Game GetRequiredGame(Guid id) =>
    _games.TryGetValue(id, out var game)
        ? game
        : throw new KeyNotFoundException("Game not found.");

    private static Game? GetGameStatic(ConcurrentDictionary<Guid, Game> games, Guid id) =>
        games.TryGetValue(id, out var game) ? game : null;

    public static GameResponse ToResponse(Game game, Scoreboard scoreboard)
    {
        var board = new string?[3][];

        for (var r = 0; r < 3; r++)
        {
            board[r] = new string?[3];

            for (var c = 0; c < 3; c++)
            {
                board[r][c] = game.Board[r, c]?.ToString();
            }
        }

        return new GameResponse
        {
            GameId = game.Id,
            Board = board,
            CurrentPlayer = game.CurrentPlayer,
            GameMode = game.Mode,
            GameStatus = game.Status,
            Winner = game.Winner,
            WinningCells = game.WinningCells.Select(x => new[] { x[0], x[1] }).ToList(),
            MoveHistory = game.Moves.Select(m => new Move
            {
                MoveNumber = m.MoveNumber,
                Player = m.Player,
                Row = m.Row,
                Column = m.Column
            }).ToList(),
            Scoreboard = scoreboard
        };
    }

    private static Scoreboard CopyScoreboard(Scoreboard source) =>
        new() { XWins = source.XWins, OWins = source.OWins, Draws = source.Draws };
}
